version: '2'
services:
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    container_name: nginx
    volumes:
      - ./:/var/www:cached
    ports:
      - "8080:80"
    links:
      - app

  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    container_name: php
    volumes:
      - ./:/var/www:cached
    links:
      - database
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
  
  database:
    image: mysql:8.0
    container_name: mysql
    environment:
        MYSQL_ROOT_PASSWORD: laundry-app-pamungkas
        MYSQL_DATABASE: laundryDB
    ports:
        - "33061:3306"

  cache:
    image: redis:3.0
    container_name: redis
    ports: 
      - "63791:6379"